### ISSUE TITLE
Support monolog 3 / laravel 10

### ISSUE THREAD

**Issue by jez500** [amazeeio/laravel_lagoon_logs#4]
Hello! 

[Laravel 10](https://laravel.com/docs/10.x/upgrade#monolog-3) now depends on [monolog 3](https://packagist.org/packages/monolog/monolog). 

Is it possible to get the `monolog/monolog` dependency version changed from `^2.01` to `^2.0|^3.0`

Currently this package cannot be used on a laravel 10+ project

**Comment by tobybellwood** [comment]
Thanks @jez500  we’ll look at this, apologies it slipped through!

**Comment by uandco** [comment]
@tobybellwood do you have a timeline in mind? It's a major blocker for those who want to start using Laravel 10.

**Comment by bomoko** [comment]
Hi all, this should be sorted in the release I'm just doing. I've tried testing it reasonably - but anyone else taking a look would be highly appreciated.

**Comment by uandco** [comment]
Thanks a lot @bomoko , I just installed 0.0.5, will report if I notice any issue, but the new project we use Laravel 10 with won't be deployed any time soon.

**Comment by bomoko** [comment]
Thanks a lot @uandco , I'd appreciate that. I'll do some more testing tomorrow.
If we're happy, it's probably time to release a version 1.0.0
